### ISSUE TITLE
KeyError from config file of qlib

### ISSUE THREAD

**Issue by plpycoin** [microsoft/qlib-server#16]
There's no default key in _default_config struction:

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    init(config)
  File "/code/qlib-server/qlib_server/config.py", line 127, in init
    redis_host=C["redis_host"],
  File "/opt/conda/lib/python3.7/site-packages/qlib/__init__.py", line 59, in init
    if C["auto_mount"]:
  File "/opt/conda/lib/python3.7/site-packages/qlib/config.py", line 37, in __getitem__
    return self.__dict__["_config"][key]
KeyError: 'auto_mount'

**Comment by Mandy007-cu** [comment]
Make sure that the **provider_uri** path exist
